module.exports = [
  {
    title: 'Understanding Stress: What It Is and How It Affects You',
    description: 'A comprehensive guide to understanding the physical and psychological effects of stress.',
    body: 'Stress is a natural physical and mental reaction to life experiences. Everyone expresses stress from time to time. Anything from everyday responsibilities like work and family to serious life events such as a new diagnosis, war, or the death of a loved one can trigger stress.\n\nFor immediate, short-term situations, stress can be beneficial to your health. It can help you cope with potentially serious situations. Your body responds to stress by releasing hormones that increase your heart and breathing rates and ready your muscles to respond.\n\nYet if your stress response does not stop firing, and these stress levels stay elevated far longer than is necessary for survival, it can take a toll on your health. Chronic stress can cause a variety of symptoms and affect your overall well-being.',
    type: 'article',
    topic: 'Stress',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['stress', 'education', 'basics', 'mental-health'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'Box Breathing: A Simple Technique for Instant Calm',
    description: 'Learn the box breathing technique used by Navy SEALs and first responders to manage stress.',
    body: 'Box breathing, also known as square breathing, is a technique used when taking slow, deep breaths. It can heighten performance and concentration while also being a powerful stress reliever. It is also called four-square breathing.\n\nHow to practice box breathing:\n1. Breathe in counting to four slowly. Feel the air enter your lungs.\n2. Hold your breath for 4 seconds. Try to avoid inhaling or exhaling for 4 seconds.\n3. Slowly exhale through your mouth for 4 seconds.\n4. Hold your breath again for 4 seconds.\n5. Repeat steps 1 through 4 at least three times, ideally for 4 minutes or until calm returns.\n\nBox breathing is a simple but powerful relaxation technique that can return your breathing pattern to a relaxed rhythm. It can clear and calm your mind, improving your focus.',
    type: 'exercise',
    topic: 'Breathing',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['breathing', 'exercise', 'stress-relief', 'relaxation', 'calm'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'The 4-7-8 Breathing Technique for Better Sleep',
    description: 'A guided breathing exercise that promotes relaxation and helps you fall asleep faster.',
    body: 'The 4-7-8 breathing technique, also known as relaxing breath, involves breathing in for 4 seconds, holding the breath for 7 seconds, and exhaling for 8 seconds. This breathing pattern aims to reduce anxiety or help people get to sleep.\n\nSome proponents claim that the method helps people get to sleep in just one minute. There is limited scientific research to support these claims, but there is a lot of anecdotal evidence to suggest that this type of deep, rhythmic breathing is relaxing and may help ease people into sleep.\n\nThe technique works by activating the parasympathetic nervous system, which is responsible for the body\'s rest-and-digest response. By extending the exhalation, you signal to your body that it is safe to relax.',
    type: 'exercise',
    topic: 'Sleep',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['sleep', 'breathing', 'relaxation', 'insomnia', 'exercise'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'Understanding Anxiety: Types, Symptoms, and Coping Strategies',
    description: 'Learn about different types of anxiety and evidence-based strategies for managing symptoms.',
    body: 'Anxiety is your body\'s natural response to stress. It is a feeling of fear or apprehension about what is to come. The first day of school, going to a job interview, or giving a speech may cause most people to feel fearful and nervous.\n\nBut if your feelings of anxiety are extreme, last for at least 6 months, and are interfering with your life, you may have an anxiety disorder. Anxiety disorders are the most common form of emotional disorder and can affect anyone.\n\nCommon coping strategies include: practicing mindfulness meditation, limiting caffeine and alcohol intake, maintaining a regular sleep schedule, exercising regularly, and challenging negative thought patterns. If anxiety is significantly affecting your daily life, speaking with a mental health professional is recommended.',
    type: 'article',
    topic: 'Anxiety',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['anxiety', 'education', 'coping', 'mental-health'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'Sleep Hygiene: Building a Better Bedtime Routine',
    description: 'Practical tips for improving your sleep quality through better habits.',
    body: 'Sleep hygiene refers to healthy sleep habits that can improve your ability to fall asleep and stay asleep. Good sleep hygiene is important because of how crucial getting good sleep is for your mental health, physical health, and overall quality of life.\n\nKey sleep hygiene practices include: keeping a consistent sleep schedule (same bedtime and wake time every day), making your bedroom comfortable, cool, dark, and quiet, removing electronic devices from the bedroom, avoiding large meals, caffeine, and alcohol before bedtime, getting regular exercise during the day, and reducing fluid intake before bed.\n\nCreating a relaxing pre-sleep routine such as reading, gentle stretching, or meditation can also signal to your body that it is time to wind down.',
    type: 'article',
    topic: 'Sleep',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['sleep', 'habits', 'routine', 'self-care'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'Introduction to Mindfulness Meditation',
    description: 'A beginner-friendly guide to practicing mindfulness for stress reduction and mental clarity.',
    body: 'Mindfulness is the basic human ability to be fully present, aware of where we are and what we are doing, and not overly reactive or overwhelmed by what is going on around us. While mindfulness is something we all naturally possess, it is more readily available to us when we practice on a daily basis.\n\nTo practice mindfulness meditation: find a quiet and comfortable place, set a time limit (even 5 minutes is a good start), notice your body and settle into a comfortable position, feel your breath as it goes in and out, notice when your mind has wandered and gently return your attention to the breath.\n\nRegular mindfulness practice has been shown to reduce stress, improve focus, decrease emotional reactivity, and promote overall well-being. It is not about stopping thoughts but about becoming a more aware observer of them.',
    type: 'article',
    topic: 'Mindfulness',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['mindfulness', 'meditation', 'stress-relief', 'awareness'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'Cognitive Distortions: Recognizing Unhelpful Thinking Patterns',
    description: 'Learn about common cognitive distortions from CBT and how to challenge them.',
    body: 'Cognitive distortions are habitual ways of thinking that are often inaccurate and negatively biased. They were first identified by Aaron Beck in the 1960s as part of his work on Cognitive Behavioral Therapy (CBT).\n\nCommon cognitive distortions include: All-or-nothing thinking (seeing things in black and white), Catastrophizing (expecting the worst), Mind reading (assuming you know what others think), Overgeneralization (making broad conclusions from a single event), Should statements (rigid rules about how things ought to be), and Emotional reasoning (assuming feelings reflect reality).\n\nThe first step to overcoming cognitive distortions is awareness. When you notice a negative thought, pause and ask yourself: Is this thought based on facts or feelings? Am I jumping to conclusions? What would I tell a friend in this situation?',
    type: 'article',
    topic: 'CBT',
    difficulty: 'intermediate',
    riskLevel: 'low',
    tags: ['cbt', 'thinking-patterns', 'mental-health', 'therapy'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'Progressive Muscle Relaxation Exercise',
    description: 'A guided exercise for releasing physical tension and reducing anxiety.',
    body: 'Progressive Muscle Relaxation (PMR) is a technique where you tense and then relax each muscle group in your body. This practice helps you become more aware of physical sensations and learn the difference between tension and relaxation.\n\nHow to practice PMR:\n1. Find a comfortable position sitting or lying down.\n2. Take a few deep breaths to start.\n3. Starting with your feet, tense the muscles as tightly as you can for about 5 seconds.\n4. Release the tension suddenly and notice the feeling of relaxation for 15-20 seconds.\n5. Move up through your body: calves, thighs, abdomen, chest, hands, arms, shoulders, neck, and face.\n6. Tense and release each group.\n\nWith practice, you will become better at recognizing and relieving tension throughout your day. This technique is particularly helpful before bed or during moments of high anxiety.',
    type: 'exercise',
    topic: 'Relaxation',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['relaxation', 'exercise', 'anxiety', 'tension', 'body'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'Digital Wellness: Managing Your Screen Time',
    description: 'Practical strategies for building a healthier relationship with technology.',
    body: 'In our constantly connected world, it is easy to spend more time on screens than we intend. While technology offers many benefits, excessive screen time, especially social media, has been linked to increased anxiety, depression, sleep problems, and reduced attention spans.\n\nStrategies for digital wellness: Set specific times to check your phone and social media rather than checking constantly. Use built-in screen time tracking tools to monitor your usage. Create phone-free zones, especially the bedroom. Turn off non-essential notifications. Practice the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds.\n\nRemember, the goal is not to eliminate technology but to use it intentionally. Ask yourself: Am I using this tool, or is it using me? Building awareness around your digital habits is the first step toward a healthier relationship with technology.',
    type: 'article',
    topic: 'Digital Wellness',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['digital-wellness', 'screen-time', 'social-media', 'habits'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'The Power of Journaling for Mental Health',
    description: 'Explore how regular journaling can improve self-awareness and emotional processing.',
    body: 'Journaling is one of the most accessible and effective tools for mental health. Writing about your thoughts and feelings can help you process emotions, identify patterns, reduce stress, and gain clarity on challenging situations.\n\nResearch shows that expressive writing can improve mood, reduce symptoms of depression and anxiety, and even strengthen immune function. You do not need to be a skilled writer; the goal is self-expression, not literary quality.\n\nGetting started with journaling: Set aside 10-15 minutes daily. Write freely without judging your thoughts. You can use prompts like: What am I feeling right now? What went well today? What is on my mind? What am I grateful for? There is no right or wrong way to journal. The most important thing is consistency.',
    type: 'article',
    topic: 'Journaling',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['journaling', 'self-awareness', 'mental-health', 'writing'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'Building Resilience: Bouncing Back from Challenges',
    description: 'Evidence-based strategies for developing psychological resilience.',
    body: 'Resilience is the ability to adapt and recover from adversity, trauma, tragedy, or significant stress. It does not mean you do not experience difficulty or distress, but rather that you are able to work through challenges and grow from them.\n\nKey factors that contribute to resilience include: maintaining strong social connections, having a positive self-image, developing problem-solving skills, managing strong feelings and impulses, making realistic plans and carrying them out, and maintaining a hopeful outlook.\n\nYou can build resilience by: nurturing supportive relationships, accepting that change is a part of life, setting realistic goals and taking decisive action, looking for opportunities for self-discovery, and taking care of yourself through exercise, sleep, and healthy eating.',
    type: 'article',
    topic: 'Resilience',
    difficulty: 'intermediate',
    riskLevel: 'low',
    tags: ['resilience', 'growth', 'coping', 'mental-health'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'When to Seek Professional Help',
    description: 'Understanding when self-help is not enough and professional support is needed.',
    body: 'While self-care strategies and wellness tools like Mindwell can be very helpful, there are times when professional support is essential. It is important to recognize when your challenges require more than what self-help can provide.\n\nConsider seeking professional help if: your symptoms persist for more than two weeks despite self-care efforts, you are having difficulty functioning at work, school, or in relationships, you are using substances to cope, you are having thoughts of self-harm or suicide, your anxiety or depression is getting worse over time, you have experienced a traumatic event.\n\nSeeking help is a sign of strength, not weakness. Mental health professionals can provide evidence-based treatments like therapy and, when appropriate, medication that can significantly improve your quality of life. Mindwell can help you connect with verified professionals who specialize in your areas of concern.',
    type: 'article',
    topic: 'Professional Help',
    difficulty: 'beginner',
    riskLevel: 'moderate',
    tags: ['professional-help', 'therapy', 'mental-health', 'support'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'Self-Care Fundamentals: Beyond Bubble Baths',
    description: 'A practical guide to building a sustainable self-care routine.',
    body: 'Self-care is often trivialized as indulgence, but true self-care involves making consistent choices that support your physical, mental, and emotional wellbeing. It is not selfish; it is necessary.\n\nThe pillars of self-care include: Physical (sleep, nutrition, exercise, hydration), Emotional (processing feelings, setting boundaries, self-compassion), Social (maintaining meaningful connections, asking for help), Mental (learning, challenging yourself, limiting information overload), and Spiritual (finding purpose, practicing gratitude, connecting with nature).\n\nBuilding a sustainable self-care routine: Start small with one or two practices. Schedule self-care like you would any important appointment. Pay attention to what genuinely recharges you versus what is just distraction. Be flexible and adjust as your needs change.',
    type: 'article',
    topic: 'Self-Care',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['self-care', 'wellness', 'habits', 'routine'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'Understanding Mood Patterns and Emotional Awareness',
    description: 'Learn to recognize and understand your mood patterns for better emotional health.',
    body: 'Emotional awareness is the ability to recognize, understand, and accept your emotions. Many people go through their days without pausing to check in with how they are actually feeling. Tracking your mood over time can reveal important patterns.\n\nCommon mood patterns to watch for: time-of-day patterns (feeling worse in the morning or evening), weekly patterns (weekend versus weekday differences), seasonal patterns, patterns related to sleep, exercise, or social interaction, and patterns connected to specific situations or people.\n\nBy tracking your mood daily, even with a simple 1-10 scale, you can start to identify triggers, recognize early warning signs, and make informed decisions about your self-care. This is why daily mood tracking is a core part of the Mindwell experience.',
    type: 'article',
    topic: 'Mood',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['mood', 'emotional-awareness', 'tracking', 'patterns'],
    published: true,
    author: 'Mindwell Team'
  },
  {
    title: 'Healthy Routine Building: Small Steps, Big Changes',
    description: 'How to build and maintain healthy daily routines that support your wellbeing.',
    body: 'Building healthy routines is one of the most effective ways to improve your mental health over time. Routines reduce decision fatigue, create stability, and help build positive habits incrementally.\n\nThe science of habit formation tells us that habits consist of three components: a cue (trigger), a routine (behavior), and a reward (benefit). To build a new habit, attach it to an existing routine. For example, practice a 2-minute breathing exercise right after brushing your teeth in the morning.\n\nTips for building routines: Start with just one new habit at a time. Make it so small it is hard to say no (e.g., one minute of meditation, not thirty). Track your consistency. Be patient; research suggests it takes 66 days on average to form a new habit. If you miss a day, just resume the next day without self-judgment.',
    type: 'article',
    topic: 'Habits',
    difficulty: 'beginner',
    riskLevel: 'low',
    tags: ['habits', 'routine', 'behavior-change', 'wellness'],
    published: true,
    author: 'Mindwell Team'
  }
];
